services:
  db:
    image: mysql/mysql-server:latest
    command:
      - --bind-address=0.0.0.0
    ports:
      - 3310:3306
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=test1234!
      - MYSQL_DATABASE=test_database
